kind: pipeline
type: docker
name: default

steps:
- name: testbench
  image: metalfs/sdk:webpack-psl8
  commands:
    - /bin/bash -c "make test"

- name: simulation-model
  image: metalfs/sdk:webpack-psl8
  commands:
    - make model
